### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference

### ISSUE THREAD

**Issue by hexi** [akaita/RxJava2Debug#3]
12-07 08:16:41.066 13893-13893/? E/NewsListAdapter: notifyDataSetChanged
12-07 08:16:41.516 2740-22749/? E/getCommonFilePath: getCommonFilePath error
12-07 08:16:41.536 30822-5438/? E/AppStore.Wave: keyUrl is empty
12-07 08:16:46.806 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:16:46.866 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:16:48.156 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:16:48.596 2417-2990/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: ICC ID is null or empty.
12-07 08:16:50.766 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:16:51.466 22800-22800/com.baidao.futures E/FuturesApp: Fatal Exception thrown on Scheduler.
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5628)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference
at com.akaita.java.rxjava2debug.ExceptionUtils.collapseCauses(ExceptionUtils.java:60)
at com.akaita.java.rxjava2debug.ExceptionUtils.setRootCause(ExceptionUtils.java:37)
at com.akaita.java.rxjava2debug.RxJava2Debug.getEnhancedStackTrace(RxJava2Debug.java:74)
at com.baidao.retrofitadapter2.YtxHttpObserver.onError(YtxHttpObserver.java:51)
at hu.akarnokd.rxjava2.debug.ObservableOnAssembly$OnAssemblyObserver.onError(ObservableOnAssembly.java:60)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
at android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5628) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
12-07 08:16:51.466 22800-22800/com.baidao.futures E/Tinker.SampleUncaughtExHandler: uncaughtException:Fatal Exception thrown on Scheduler.
12-07 08:16:51.476 22800-22800/com.baidao.futures E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5628)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference
            at com.akaita.java.rxjava2debug.ExceptionUtils.collapseCauses(ExceptionUtils.java:60)
            at com.akaita.java.rxjava2debug.ExceptionUtils.setRootCause(ExceptionUtils.java:37)
            at com.akaita.java.rxjava2debug.RxJava2Debug.getEnhancedStackTrace(RxJava2Debug.java:74)
            at com.baidao.retrofitadapter2.YtxHttpObserver.onError(YtxHttpObserver.java:51)
            at hu.akarnokd.rxjava2.debug.ObservableOnAssembly$OnAssemblyObserver.onError(ObservableOnAssembly.java:60)
            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
            at android.os.Handler.handleCallback(Handler.java:739) 
            at android.os.Handler.dispatchMessage(Handler.java:95) 
            at android.os.Looper.loop(Looper.java:148) 
            at android.app.ActivityThread.main(ActivityThread.java:5628) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
12-07 08:16:51.476 22800-22800/com.baidao.futures E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.baidao.futures, PID: 22800
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5628)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference
    at com.akaita.java.rxjava2debug.ExceptionUtils.collapseCauses(ExceptionUtils.java:60)
    at com.akaita.java.rxjava2debug.ExceptionUtils.setRootCause(ExceptionUtils.java:37)
    at com.akaita.java.rxjava2debug.RxJava2Debug.getEnhancedStackTrace(RxJava2Debug.java:74)
    at com.baidao.retrofitadapter2.YtxHttpObserver.onError(YtxHttpObserver.java:51)
    at hu.akarnokd.rxjava2.debug.ObservableOnAssembly$OnAssemblyObserver.onError(ObservableOnAssembly.java:60)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5628) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
12-07 08:16:52.006 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:16:52.096 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_sun.png: open failed: ENOENT (No such file or directory)
12-07 08:16:52.096 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_degree.png: open failed: ENOENT (No such file or directory)
12-07 08:16:52.096 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_minus.png: open failed: ENOENT (No such file or directory)
12-07 08:17:00.016 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:17:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:17:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:17:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:17:40.306 2417-2965/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: ICC ID is null or empty.
12-07 08:17:40.366 22951-23001/com.baidao.futures E/PushIntentService: onReceiveClientId -> clientid = 580f1e13985a5e750773f1ad9fc540f4
12-07 08:18:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:18:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:18:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:18:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:18:08.036 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:18:08.036 2475-2475/? E/Launcher.DropTarget: Workspace onDragStart: Drag contract violated: 1
12-07 08:18:08.036 2475-2475/? E/Launcher.DropTarget: Workspace onDragEnter: Drag contract violated: 2
12-07 08:18:08.646 2475-2475/? E/Launcher.DropTarget: Workspace onDragExit: Drag contract violated: 1
12-07 08:18:08.806 2475-2475/? E/Launcher.DropTarget: Workspace onDragEnd: Drag contract violated: 1
12-07 08:18:11.146 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:18:11.176 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_sun.png: open failed: ENOENT (No such file or directory)
12-07 08:18:11.176 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_degree.png: open failed: ENOENT (No such file or directory)
12-07 08:18:11.186 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_minus.png: open failed: ENOENT (No such file or directory)
12-07 08:18:15.656 1394-1810/? E/qti_sensors_hal: w_orient output WORT 0 60 6
12-07 08:18:15.726 1394-1810/? E/qti_sensors_hal: w_orient output WORT 0 58 6
12-07 08:18:15.776 1394-1810/? E/qti_sensors_hal: w_orient output WORT 0 57 6
12-07 08:18:15.846 1394-1810/? E/qti_sensors_hal: w_orient output WORT 0 56 8
12-07 08:18:15.906 1394-1810/? E/qti_sensors_hal: w_orient output WORT 0 55 9
12-07 08:18:16.296 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:18:18.416 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:18:18.756 22951-23049/com.baidao.futures E/PushIntentService: onReceiveClientId -> clientid = 580f1e13985a5e750773f1ad9fc540f4
12-07 08:18:20.896 1394-1810/? E/qti_sensors_hal: w_orient output WORT 3 59 287
12-07 08:18:20.956 1394-1810/? E/qti_sensors_hal: w_orient output WORT 3 58 283
12-07 08:18:21.016 1394-1810/? E/qti_sensors_hal: w_orient output WORT 3 56 281
12-07 08:18:21.076 1394-1810/? E/qti_sensors_hal: w_orient output WORT 3 55 283
12-07 08:18:21.196 1394-1810/? E/qti_sensors_hal: w_orient output WORT 3 53 283
12-07 08:18:22.036 1394-1810/? E/qti_sensors_hal: w_orient output WORT -1 78 0
12-07 08:18:22.096 1394-1810/? E/qti_sensors_hal: w_orient output WORT -1 79 0
12-07 08:18:22.166 1394-1810/? E/qti_sensors_hal: w_orient output WORT -1 81 0
12-07 08:18:22.216 1394-1810/? E/qti_sensors_hal: w_orient output WORT -1 82 0
12-07 08:18:22.276 1394-1810/? E/qti_sensors_hal: w_orient output WORT -1 82 0
12-07 08:18:32.996 1394-1853/? E/native: do suspend false
12-07 08:18:33.066 1394-1853/? E/WifiStateMachine: handleIPv4Success vivoDhcpHistoryLeaseTime 1512605920274
12-07 08:18:33.106 1394-1888/? E/VivoBandWidthCollect: Unhandled message { when=-2ms what=137473 obj=Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } target=com.android.internal.util.StateMachine$SmHandler } in state VivoWifiConnectedState
12-07 08:18:33.126 1394-1853/? E/wifi_gbk2utf: g_pItemList is NULL
12-07 08:18:33.146 1394-1853/? E/native: do setRoamMode true
12-07 08:19:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:19:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:19:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:19:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:19:41.026 1394-1462/? E/ActivityManager: ANR in com.baidao.futures
PID: 22951
Reason: Broadcast of Intent { act=MqttService.pingSender.dd340806-a3b4-4f6e-ac7d-7c579e723a9e flg=0x14 (has extras) }
12-07 08:20:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:20:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:20:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:20:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:21:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:21:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:21:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:21:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:21:38.996 1394-1462/? E/ActivityManager: ANR in com.baidao.futures
PID: 22951
Reason: executing service com.baidao.futures/.support.notification.igexin.PushIntentService
12-07 08:21:41.586 2740-22661/? E/TcpNetwork: recv() SocketException java.net.SocketException: Socket closed
12-07 08:22:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:22:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:22:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:22:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:23:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:23:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:23:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:23:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:24:00.016 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:24:00.016 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:24:00.016 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:24:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:24:43.076 1394-1460/? E/SyncManager: Bind attempt failed - target: ComponentInfo{com.qihoo.appstore/com.qihoo.appstore.keepalive.account.SyncServiceNew}
12-07 08:24:43.086 1394-1460/? E/SyncManager: Bind attempt failed - target: ComponentInfo{com.ss.android.article.news/com.ss.android.account.AccountSyncService}
12-07 08:25:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:25:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:25:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:25:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:26:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:26:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:26:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:26:00.026 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:27:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:27:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:27:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:27:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:28:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
12-07 08:28:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
12-07 08:28:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
12-07 08:28:00.036 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
12-07 08:28:01.386 3159-3171/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-07 08:28:01.426 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_sun.png: open failed: ENOENT (No such file or directory)
12-07 08:28:01.426 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_degree.png: open failed: ENOENT (No such file or directory)
12-07 08:28:01.426 2475-2560/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_minus.png: open failed: ENOENT (No such file or directory)
12-07 08:28:07.806 22951-22951/com.baidao.futures E/YtxHttpObserver: The mapper function returned a null value.
 java.lang.Throwable
 Caused by: java.lang.Throwable
 Caused by: java.lang.Throwable
     at io.reactivex.Observable.map(Observable.java:8630)
     at com.baidao.futures.module.home.model.HomeModel.loadHomePageDialogData(HomeModel.java:30)
     at com.baidao.futures.module.home.HomePresenter.loadHomeDialogData(HomePresenter.java:67)
     at com.baidao.futures.module.home.HomePresenter.onViewCreated(HomePresenter.java:52)
     at com.baidao.library.lifecycle.FragmentLifecycle.onViewCreated(FragmentLifecycle.java:29)
     at com.baidao.library.lifecycle.SupportLifecycleFragment.onViewCreated(SupportLifecycleFragment.java:136)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2149)
     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2095)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1133)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2149)
     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:600)
     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
     at com.futures.appframework.BaseActivity.onStart(BaseActivity.java:161)
     at com.baidao.futures.module.MainActivity.onStart(MainActivity.java:208)
     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
     at android.app.Activity.performStart(Activity.java:6336)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2480)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
     at android.app.ActivityThread.access$1000(ActivityThread.java:166)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5628)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by hexi** [comment]
The exception occured because i call `RxJava2Debug.getEnhancedStackTrace(throwable)` in the main thread。why can not call it in the main thread?

**Comment by akaita** [comment]
This looks the same as #2 .
Can you give a try to version 1.2.2 ?

**Comment by akaita** [comment]
It has been 9 days since the release of 1.2.2, which should solve this issue.
@hexi please ping if it replicates
